services:
  pytorch-gpu-node:
    build:
      context: .
      args:
        JUPYTER_LAB_PORT: ${JUPYTER_LAB_PORT}
    ports:
      - ${JUPYTER_LAB_PORT}:${JUPYTER_LAB_PORT}
    volumes:
      - ./jupyter-data:/playground
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]