services:
  pytorch-gpu-node:
    build: windows
    ports:
      - "8088:8088"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]